//
//  CoinsListModels.swift
//  MarketCoins
//
//  Created by Maria on 14/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinsList {
  // MARK: Use cases
  
  enum FetchGlobalValues {
    struct Request {
        let baseCoin: String
    }
    struct Response {
        let baseCoin: String
        let totalMarketCap: [String: String]
        let totalVolume: [String: String]
    }
    struct ViewModel {
        struct GlobalValues {
            let title: String
            let value: String
        }
        let globalValues: [GlobalValues]
    }
  }
    
    enum FetchListCoins {
        struct Request {
            let baseCoin: String
            let orderBy: String
            let top: Int
            let pricePercentage: String
        }
        struct Response {
            let baseCoin: String
            let id: String
            let symbol: String
            let image: String
            let currentPrice: Double
            let marketCap: Double
            let marketCapRank: Int?
            let priceChangePercentage: Double
        }
        struct viewModel {
            struct Coin {
                let id: String
                let name: String
                let rank: String
                let iconURL: String
                let symbol: String
                let price: String
                let priceChangePercentage: String
                let marketCapitalization: String           
            }
            let coins: [Coin]
        }
    }
}
