//
//  CoinsListPresenter.swift
//  MarketCoins
//
//  Created by Maria on 14/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinsListPresentationLogic {
    func presentGlobalValues(response: CoinsList.FetchGlobalValues.Response)
    func presentListCoins(response: CoinsList.FetchListCoins.Response)
    func presentError(error:CryptocurrenciesError)
}

class CoinsListPresenter: CoinsListPresentationLogic {
    
    weak var viewController: CoinsListDisplayLogic?
    
    func presentGlobalValues(response: CoinsList.FetchGlobalValues.Response) {
        <#code#>
    }
    
    func presentListCoins(response: CoinsList.FetchListCoins.Response) {
        <#code#>
    }
    
    func presentError(error: CryptocurrenciesError) {
        <#code#>
    }
}
